- Gemfile
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/pets/index.html.erb
- app/views/pets/new.html.erb
Added basic html elements to home & index. Installed simple form.
> Add HTML stuff & install simpleform

- app/views/layouts/application.html.erb
- app/views/pets/index.html.erb
Added basic html elements to pets index and assured responsive behavior for entire app
> Add basic html elements to pets index

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/home.html.erb
I created a banner did some changes in html and css about image and the banner text.
> banner done

- app/assets/stylesheets/pages/_home.scss
- app/controllers/pets_controller.rb
- app/views/layouts/application.html.erb
- app/views/pets/_form.html.erb
- app/views/pets/index.html.erb
- app/views/pets/new.html.erb
Added lots of stuff, let's have a look together
> Frontend stuff

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/pets/_index.scss
- app/views/pets/index.html.erb
I created and styled the pet cards for show page.
> Show page pet cards styled

- app/assets/stylesheets/components/_navbar.scss
Branch name wrong, just adjusted the logo size to 150px
> Make logo 150px

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/pets_controller.rb
- config/routes.rb
> Solve authentication

- app/views/layouts/application.html.erb
Added a link to the logo in the navbar with target home. @MichaelRosenfeld please merge.
> Make logo in navbar link_to home

- app/views/pets/show.html.erb
Added further pet details as well as an mailto-link (Contact owner!) to show page of each pet. @MichaelRosenfeld  please merge.
> Add details and mailto link to showpage

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/pets/_indexcards.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
I made and styled index cards and adjusted the size of the banner.
> index cards done

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/home.html.erb
I created icons for facebook,instagram,twitter,etc.
> Footer is done

- app/views/pages/home.html.erb
Removed duplicate content from home page. @MichaelRosenfeld please merge.
> Remove duplicate content

- app/assets/stylesheets/pages/pets/_index.scss
- app/views/pets/index.html.erb
- app/views/pets/show.html.erb
Pets index is now flexbox and displays the images that have been uploaded while creating pets. @MichaelRosenfeld please merge ;)
> Add cloudinary to index

- app/assets/stylesheets/components/_banner.scss
I made the banner to appear with a random image with every refresh.
> e banner with random images

- app/views/layouts/application.html.erb
Added lings behind avatar. @MichaelRosenfeld please please merge
> Change links behind avatar

- app/controllers/pets_controller.rb
- app/views/pages/home.html.erb
- db/seeds.rb
Please merge this, @MichaelRosenfeld. Many thanks upfront.
> Add links home

- app/controllers/pets_controller.rb
- app/views/pages/home.html.erb
- db/seeds.rb
Please merge @MichaelRosenfeld
> Links behind category symbols

- app/controllers/pets_controller.rb
- app/views/pets/edit.html.erb
- app/views/pets/show.html.erb
Added the edit functionality to the pet show page. @MichaelRosenfeld could you please merge?
> Add edit function to pet

- app/views/pets/show.html.erb
Simply added a "Back to all pets" button to the pet show page. @MichaelRosenfeld could you please merge? Many thanks!
> Add back to all pets button to show page

- app/views/pages/home.html.erb
- app/views/pets/show.html.erb
- db/seeds.rb
Added a button to the homepage to be able to directly create a new pet. @MichaelRosenfeld could you merge once again, please? Many thanks!
> Homepage button

- app/assets/stylesheets/pages/pets/_indexcards.scss
- app/views/pages/home.html.erb
Changed image circles on home page to be flexbox with flex-wrap: wrap for responsiveness. @MichaelRosenfeld please merge ;) many thanks.
> Make image circles on home page responsive

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/pets/_show.scss
- app/views/pages/home.html.erb
- app/views/pets/show.html.erb
Changed button style for some buttons (home, show) and added card layout to pet show page. Please merge, @MichaelRosenfeld
> Buttons & Show page

- app/controllers/pets_controller.rb
Added skip login in pet controller so that users that aren't logged in can still access pet index & show. @MichaelRosenfeld please merge ;) Merci!
> Add skip login for index & show

- app/views/pages/home.html.erb
- app/views/pets/_form.html.erb
- app/views/pets/create.html.erb
Added a selectable collection (dropdown) for pet species and made sure, that :query is being populated correctly. @MichaelRosenfeld could you please merge? Many thanks!
> Species collection

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/pets_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/views/pets/_info_window.html.erb
- app/views/pets/create.html.erb
- db/schema.rb
- package.json
- yarn.lock
Reverts MichaelRosenfeld/petsbnb#47
> Revert "Map Markers Pop-Up Windows & Map Search Implemented & Tested"

- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Changed home page text so that Sascha doesn't feel useless... and also assured that footer is present on all pages. @MichaelRosenfeld please merge ;) Thx!
> Change home page text and make footer available on all pages

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
Made the login pages look a little bit nicer and changed the Register-link in the navbar dropdown to actually link to the register page
> Make devise views look good and change register link in navbar

- app/assets/stylesheets/pages/pets/_index.scss
- app/views/pets/index.html.erb
> Display map alongside cards
